#!/bin/sh
# Prints the current volume or 🔇 if muted.
vol="$(mixer -o | perl -ne '/vol.volume/ and print ' | perl -F: -lane 'print @F[1]' | perl -pe 's/0\.//g'  )"
mute="$(mixer -o | perl -ne '/vol.mute/ and print' | perl -F= -lane 'print @F[1]')"
# If muted, print 🔇 and exit.
[ "$mute" == "on" ] && echo 🔇 && exit

case 1 in
	$((vol >= 70)) ) icon="🔊" ;;
	$((vol >= 30)) ) icon="🔉" ;;
	$((vol >= 1)) ) icon="🔈" ;;
	* ) echo 🔇 && exit ;;
esac

echo "$icon $vol%"
